config/routes.rb
Rails.application.routes.draw do
  resources :events
  root to: 'calendar#index'
  get 'calendar/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def index
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    start_date = params[:start]
    end_date = params[:end]
    @events = Event.where("start_time >= ? AND end_time <= ?", start_date, end_date)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to root_path
    else
      render :new
    end

  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    if @event.update(event_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:all_day, :start_time, :end_time, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/calendar/index.html.erb
<%= content_tag :div, data: { controller: 'calendar' } do %>
  <%= content_tag :div, class: 'modal', data: { target: 'calendar.modal' } do %>
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <%= form_with model: Event.new, local: true do |form| %>
          <div class="modal-body">
            <div class="field">
              <%= form.label :all_day %>
              <%= form.check_box :all_day %>
            </div>

            <div class="field">
              <%= form.label :start_time %>
              <%= form.text_field :start_time, data: { target: 'calendar.start_time' } %>
            </div>

            <div class="field">
              <%= form.label :end_time %>
              <%= form.text_field :end_time, data: { target: 'calendar.end_time' } %>
            </div>

            <div class="field">
              <%= form.label :title %>
              <%= form.text_field :title %>
            </div>
          </div>
          <div class="modal-footer">
            <%= form.submit class: 'btn btn-primary' %>
            <%= link_to "cancel", root_path, {class: "btn btn-secondary"} %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

  <%= tag :div, data: { target: 'calendar.calendar' } %>
<% end %>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :all_day %>
    <%= form.check_box :all_day %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'home', root_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>All day</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.all_day %></td>
        <td><%= event.start_time %></td>
        <td><%= event.end_time %></td>
        <td><%= event.title %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>All day:</strong>
  <%= @event.all_day %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', root_path %> |
<%= link_to "delete", event_path(@event), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>